version: '3'
services:
  postgresql:
    image: postgres:9.6.10-alpine
    environment:
      POSTGRES_PASSWORD: snello
      POSTGRES_USER: snello
      POSTGRES_DB: snello
    ports:
      - '5432:5432'
    expose:
      - 5432
  mysql:
    image: mysql:8.0.17
    restart: always
    ports:
      - '3306:3306'
    expose:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: snello
      MYSQL_DATABASE: snello
      MYSQL_USER: snello
      MYSQL_PASSWORD: snello
    command: [--character-set-server=utf8mb4,--max-connections=1000, --wait-timeout=300, --interactive-timeout=300, --collation-server=utf8mb4_unicode_ci,--default-authentication-plugin=mysql_native_password]
